### PR TITLE
sideBar visually added and frontend folder structure changed

### PR DESCRIPTION
**Pull request by shchau**
SideBar is there visually but does nothing atm.
semantics-ui-react and semantics-ui-css added.
Frontend folder structure changed so that we have a pages folder that App.js will call from.

### CODE REVIEW

**Review by shchau — COMMENTED** [review]
it good

**Comment by shchau** [comment]
> it good

thanks

**Comment by shchau** [comment]
> > it good
> 
> thanks

wth man

**Review by forgeno — APPROVED** [review]
Looks good

**Comment by derrick-w** [comment]
yes

**Review by derrick-w — APPROVED** [review]
yes

**Pull request merged**
